# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('post_time', models.DateTimeField(verbose_name='posting date')),
                ('journalist', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('keywords', models.CharField(max_length=500)),
                ('fb_like', models.IntegerField()),
                ('fb_share', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('actor', models.CharField(max_length=500)),
                ('fb_like', models.IntegerField()),
                ('post_time', models.DateTimeField(verbose_name='posting time')),
                ('source_type', models.CharField(max_length=500)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_provider.Article')),
            ],
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('actor', models.CharField(max_length=500)),
                ('fb_like', models.IntegerField()),
                ('post_time', models.DateTimeField(verbose_name='posting time')),
                ('source_type', models.CharField(max_length=500)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_provider.Comment')),
            ],
        ),
    ]
