# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
